---
apiVersion: v1
kind: Service
metadata:
  name: kafka-broker
spec:
  ports:
  - port: 9092
  # [podname].kafka-broker.kafka.svc.cluster.local
  clusterIP: None
  selector:
    app: kafka

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
spec:
  ports:
  - port: 9092
    protocol: TCP
    targetPort: 9092
    nodePort: 30092
  selector:
    app: kafka
  type: NodePort