apiVersion: v1
kind: Service
metadata:
  name: consumer
spec:
  ports: 
  - port: 9102
    name: metrics
    protocol: TCP
    targetPort: 9102
  selector:
    app: consumer
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: consumer
  name: consumer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - image: ratnadeepb/java-kafka-consumer:latest
        name: consumer
        ports:
        - containerPort: 9102
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP