apiVersion: v1
kind: Service
metadata:
  name: producer-metrics
spec:
  ports: 
  - port: 9102
    name: metrics
    protocol: TCP
    targetPort: 9102
  selector:
    app: producer
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: producer
  name: producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
      - image: ratnadeepb/java-kafka-producer:latest
        name: producer
        ports:
        - containerPort: 9102