# https://www.cloudytuts.com/guides/kubernetes/how-to-deploy-mongodb-on-kubernetes/
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector:
    app: mongodb
  ports:
  - protocol: TCP
    port: 27017