apiVersion: v1
kind: Service
metadata:
  name: producer-svc
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: producer-svc
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: producer-svc
  name: producer-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer-svc
  template:
    metadata:
      labels:
        app: producer-svc
    spec:
      containers:
        - image: ratnadeepb/java-kafka-producer:latest
          name: producer-svc
          ports:
            - containerPort: 8080
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: SEND_RATE
              value: "700"
            - name: INFLUXDB_TOKEN
              value: "n5z-MoDmPFXnDacCSquqibIZnOq3ziXaWfRRwBpV_-mjurYwQd30h0E4dn9S-t4u5-iuitaZsOL4UtVeMdE6Vw=="
              # - name: WAIT
              #   value: "2"
              # - name: WAIT_NS
              #   value: "500000"
