apiVersion: v1
kind: Service
metadata:
  name: producer-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: producer-svc
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: producer-svc
  name: producer-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer-svc
  template:
    metadata:
      labels:
        app: producer-svc
    spec:
      containers:
      - image: ratnadeepb/kafka-producer:latest
        name: producer-svc
        ports:
        - containerPort: 8080